# --------------------------------------------
# Created by pkcsloye, 2018.01.06
#            My Email is 40018117@qq.com
#
# Project dockerfiles:
#    https://github.com/pkcsloye/dockerfiles
# --------------------------------------------

FROM registry.access.redhat.com/rhel7/pod-infrastructure:latest